### ISSUE TITLE
What to expect from preallocated exp(tA)v? And what is the proper way of doing it.

### ISSUE THREAD

**Issue by ttolppanen** [SciML/ExponentialUtilities.jl#151]
**What to expect from preallocated exp(tA)v❓**

**Context**
The problem I am trying to solve is

v(t+dt) = exp(-i * H * dt) v(t),

where H is a Hermitian matrix, and v is a complex valued vector. I have solved this with my own implementation of calculating the krylov subspace, and then calculating the exponent in the krylov subspace. I am running into a problem where calculating the exponent uses too much memory (I am preallocating for the krylov subspace construction part).

I was searching for ways to calculate exp(-i * H * dt) with doing as little allocations as possible, and I found this package. I tried using lanczos! and  expv! to solve my problem. And I also tried keeping my own krylov subspace calculation part, but using the exponent! function from this package. I preallocated for both of these solutions, and in both the memory usage is still substantial, and the calculation time is _roughly_ the same in all three scenarios. The number of allocations was the same when I used lanczos! and expv!, and my own code, but with exponent! there were a lot less allocations. The memory allocated was same when I used lanczos! and expv!, and exponent!, so here I saw significant improvement over my own code. Sadly this doesnt translate to calculation time, since there is still a lot of memory being allocated (about 20GiB).

I tested the different solutions by running an actual simulation, so not in a MWE or anyting like that. There is definetly other allocations coming from the rest of the code, and the situation is complicated, so please take these results with a grain of salt.

I am surprised that the number of allocations were reduced significantly when using the exponent!, but not with using lancoz! and expv!. This makes me wonder if I am doing something wrong. I had a difficult time figuring out how to preallocate for lancoz! and expv!. From the documentation it was hard to find an explanation how to do this, but with trial and error and by reading the source code I got the code running. Anyways, what I did was
```
# here k is the dimension of the krylov subspace, d the dimension of the system
cache = ExpvCache{Float64}(k)
ks = KrylovSubspace{ComplexF64, Float64}(d, k)

lanczos!(ks, H, v)
expv!(v, -1.0im * t, ks; cache)
```
**Actual Questions**
Is this the proper way to preallocate for this problem?
Should I expect close to zero allocations for the lanczos! and expv! part?
Do you know a better way to solve this? I am open for suggestions.

**Comment by ChrisRackauckas** [comment]
That should be all that's needed. Will need an MWE

**Comment by ttolppanen** [comment]
Alright thank you, I just wanted a confirmation that I am doing things the right way.
