### ISSUE TITLE
support CUDA arrays?

### ISSUE THREAD

**Issue by GiggleLiu** [SciML/ExponentialUtilities.jl#27]
I tried to port CuArrays `CUSPARSE` module to ExponentialUtilities  to utilize GPU devices. I removed the array type restriction from `KrylovSubspace`, but still not working.

Wondering how much effort it is to write a GPU compatible `expmv` and does it worth a try?

**Comment by ChrisRackauckas** [comment]
It's definitely worth a try. Most of the operations are broadcasted along columns, so a naive algorithm would make them all actually broadcast and get rid of any indexing operations. It might be a little difficult in some spots but definitely doable.
